# Generated by Django 2.1.2 on 2018-10-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('item_no', models.IntegerField()),
                ('item_name', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('stock_location', models.CharField(max_length=100)),
                ('cost_per_unit', models.FloatField()),
                ('previous_balance', models.FloatField()),
                ('purchase', models.FloatField()),
                ('issued', models.DateField()),
                ('ending_balance', models.FloatField()),
                ('issued_to', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=500)),
            ],
        ),
    ]
