# Generated by Django 2.1.2 on 2018-10-13 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StaffWorkspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='added_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='cost_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ending_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='issued_to',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='item_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminWorkspace.Item'),
        ),
        migrations.AlterField(
            model_name='report',
            name='purchase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='stock_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminWorkspace.StockLocation'),
        ),
        migrations.AlterField(
            model_name='report',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminWorkspace.Vendor'),
        ),
    ]
