# Generated by Django 2.1.2 on 2018-10-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffWorkspace', '0002_auto_20181013_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='issued',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
