# Generated by Django 2.1.2 on 2018-10-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StaffWorkspace', '0005_auto_20181028_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='issued',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
