# Generated by Django 2.1.2 on 2018-10-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminWorkspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='balance',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
