# Generated by Django 2.1.2 on 2018-10-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminWorkspace', '0002_item_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
