# Generated by Django 2.1.2 on 2018-10-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminWorkspace', '0003_auto_20181013_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost_per_unit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='safety_stock_limit',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
